# Generated by Django 5.2.1 on 2025-10-10 19:22

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_alter_image_session_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='film',
            field=models.CharField(choices=images.models.get_film_choices, default=None, max_length=200),
        ),
    ]
