# Generated by Django 5.2.1 on 2025-10-24 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_image_film'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Image',
            new_name='ImageUpload',
        ),
    ]
