# Generated by Django 5.2.1 on 2025-10-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_rename_image_imageupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
