# Generated by Django 5.2.1 on 2025-10-28 21:17

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_imageupload_is_public'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='filtered',
            field=models.ImageField(default=None, upload_to=images.models.session_directory_path),
        ),
    ]
