# Generated by Django 5.2.1 on 2025-10-29 03:46

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_imageupload_filtered'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imageupload',
            name='is_public',
        ),
        migrations.AlterField(
            model_name='imageupload',
            name='film',
            field=models.CharField(choices=images.models.get_film_choices, default=None, max_length=200, validators=[images.models.validate_film_choice]),
        ),
    ]
