# Generated by Django 5.2.1 on 2025-11-06 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_remove_imageupload_is_public_alter_imageupload_film'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
    ]
