# Generated by Django 5.2.8 on 2026-09-22 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_imageupload_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUTUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='clut/uploads/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('film', models.CharField(max_length=200)),
                ('exposure', models.FloatField()),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
