# Generated by Django 5.2.8 on 2026-09-23 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0010_clutupload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutupload',
            name='film',
            field=models.CharField(default=None, max_length=200),
        ),
        migrations.AlterField(
            model_name='clutupload',
            name='image',
            field=models.ImageField(upload_to='CLUT/user_uploads/'),
        ),
    ]
