# Generated by Django 5.2.8 on 2026-09-23 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0011_alter_clutupload_film_alter_clutupload_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUTCreation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clut', models.ImageField(upload_to='generations/clut/')),
                ('identity', models.ImageField(upload_to='generations/identity/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('info', models.CharField(max_length=200)),
            ],
        ),
    ]
