# Generated by Django 5.2.8 on 2026-09-23 20:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0012_clutcreation'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLUTCreation',
            new_name='CLUTCreate',
        ),
    ]
