# Generated by Django 5.2.8 on 2026-09-24 00:56

import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0013_rename_clutcreation_clutcreate'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutcreate',
            name='sample',
            field=models.ImageField(default=None, upload_to=images.models.sample_directory_path),
        ),
        migrations.AddField(
            model_name='clutcreate',
            name='session_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='clutcreate',
            name='clut',
            field=models.ImageField(default=None, upload_to=images.models.clut_directory_path),
        ),
        migrations.AlterField(
            model_name='clutcreate',
            name='identity',
            field=models.ImageField(default=None, upload_to=images.models.identity_directory_path),
        ),
    ]
