# Generated by Django 5.2.8 on 2026-09-24 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0014_clutcreate_sample_clutcreate_session_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutcreate',
            name='clut',
            field=models.ImageField(default=None, upload_to=''),
        ),
    ]
