# Generated by Django 5.2.8 on 2026-09-25 19:01

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0015_alter_clutcreate_clut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutcreate',
            name='clut',
            field=models.ImageField(default=None, upload_to=images.models.clut_directory_path),
        ),
    ]
