# Generated by Django 5.2.1 on 2026-09-30 22:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0017_alter_clutcreate_clut'),
    ]

    operations = [
        migrations.AddField(
            model_name='imageupload',
            name='id_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
