# Generated by Django 5.2.1 on 2026-09-30 22:36

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0018_imageupload_id_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutcreate',
            name='id_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name='clutupload',
            name='id_slug',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
