# Generated by Django 5.2.8 on 2026-10-01 03:01

import django.db.models.deletion
import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0019_clutcreate_id_slug_clutupload_id_slug'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='clutupload',
            name='session_key',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session'),
        ),
        migrations.AlterField(
            model_name='clutupload',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=images.models.uploaded_clut_directory_path),
        ),
    ]
