# Generated by Django 5.2.8 on 2026-10-01 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0020_clutupload_session_key_alter_clutupload_image'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CLUTCreate',
            new_name='CLUTGenerate',
        ),
    ]
