# Generated by Django 5.2.8 on 2026-10-02 00:56

import django.db.models.deletion
import images.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0021_rename_clutcreate_clutgenerate'),
        ('sessions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CLUTCreator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_slug', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('clut', models.ImageField(blank=True, null=True, upload_to=images.models.clut_directory_path)),
                ('sample', models.ImageField(default=None, upload_to=images.models.sample_directory_path)),
                ('identity', models.ImageField(default=None, upload_to=images.models.identity_directory_path)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('filename', models.CharField(max_length=100)),
                ('session_key', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='sessions.session')),
            ],
        ),
        migrations.DeleteModel(
            name='CLUTGenerate',
        ),
    ]
