# Generated by Django 5.2.8 on 2026-10-05 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0022_clutcreator_delete_clutgenerate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imageupload',
            old_name='id_slug',
            new_name='short_id',
        ),
    ]
