# Generated by Django 5.2.8 on 2026-10-05 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0023_rename_id_slug_imageupload_short_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clutcreator',
            old_name='id_slug',
            new_name='short_id',
        ),
        migrations.RenameField(
            model_name='clutupload',
            old_name='id_slug',
            new_name='short_id',
        ),
    ]
