# Generated by Django 6.1.1 on 2026-10-05 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0024_rename_id_slug_clutcreator_short_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageupload',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
