# Generated by Django 5.2.1 on 2026-10-06 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0025_alter_imageupload_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutcreator',
            name='session_key',
            field=models.CharField(blank=True, db_index=True, max_length=40, null=True),
        ),
    ]
