# Generated by Django 5.2.8 on 2026-10-06 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0026_alter_clutcreator_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clutupload',
            name='exposure',
            field=models.SmallIntegerField(),
        ),
    ]
